name: Build and Release STM32 Firmware

on:
  push:
    tags:
      - "v*"  # 仅当 push tag 时触发，例如 v1.0.0

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Debug File Existence
        run: |
          ls -R cmake
          file cmake/toolchain-arm-none-eabi.cmake

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y cmake ninja-build gcc-arm-none-eabi binutils-arm-none-eabi libnewlib-arm-none-eabi
          ninja --version  # 确保 ninja 正确安装

      - name: Configure CMake
        run: |
          cmake -S . -B build -G Ninja \
            -DCMAKE_MAKE_PROGRAM=/usr/bin/ninja \
            -DCMAKE_TOOLCHAIN_FILE=${{ github.workspace }}/cmake/toolchain-arm-none-eabi.cmake \
            -DCMAKE_BUILD_TYPE=Release

      - name: Build firmware
        run: |
          cmake --build build --parallel

      - name: Convert ELF to BIN and HEX
        run: |
          arm-none-eabi-objcopy -O binary build/firmware.elf build/firmware.bin
          arm-none-eabi-objcopy -O ihex build/firmware.elf build/firmware.hex

      - name: Upload firmware artifacts
        uses: actions/upload-artifact@v4
        with:
          name: firmware
          path: |
            build/firmware.elf
            build/firmware.bin
            build/firmware.hex
