name: Build and Release STM32 Firmware

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y cmake ninja-build gcc-arm-none-eabi binutils-arm-none-eabi libnewlib-arm-none-eabi

      - name: Verify Ninja Installation
        run: |
          ninja --version

      - name: Configure CMake
        run: |
          cmake -DCMAKE_BUILD_TYPE=Debug -DCMAKE_MAKE_PROGRAM=ninja -G Ninja -S . -B build -DPROJECT_NAME="firmware"

      - name: Build firmware
        run: |
          cmake --build build --parallel
          

      - name: Convert ELF to BIN and HEX
        run: |
          cp build/*.hex build/firmware.hex
          cp build/*.bin build/firmware.bin
          cp build/*.elf build/firmware.elf

      - name: Upload firmware artifacts
        uses: actions/upload-artifact@v4
        with:
          name: firmware
          path: |
            build/firmware.elf
            build/firmware.bin
            build/firmware.hex

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: firmware
          path: build

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            build/firmware.elf
            build/firmware.bin
            build/firmware.hex
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
